### ISSUE TITLE
Add method to set laas-accent-snippets into documentation

### ISSUE THREAD

**Issue by K-gihu** [tecosaur/LaTeX-auto-activating-snippets#18]
I need to change `,. -> \vec{}` snippet to `,. -> \symbfit{}` and I figured out to copy code [here](https://github.com/tecosaur/LaTeX-auto-activating-snippets/blob/9d6f4448347fcf48d0fed51eba16423c9254c212/laas.el#L368-L383) and use a `setq` function.
```elisp
(setq laas-accent-snippets
  `(:cond laas-object-on-left-condition
    ,@(cl-loop for (key exp) in '((". " "dot")
                                  (".. " "dot")
                                  (",." "symbfit")
                                  (".," "symbfit")
                                  ("~ " "tilde")
                                  ("hat" "hat")
                                  ("bar" "overline"))
               collect :expansion-desc
               collect (format "Wrap in \\%s{}" exp)
               collect key
               ;; re-bind exp so its not changed in the next iteration
               collect (let ((expp exp)) (lambda () (interactive)
                                           (laas-wrap-previous-object expp)))))
)
```
Besides, as I have tested, this variable must be set before laas package was loaded. For example, when using use-package, this fragment of code must be put in `:init` block.

I think the method to set laas-accent-snippets should be added into document for reference.

**Comment by ymarco** [comment]
You're overcomplicating things. Just override ",." and ".," after the package is loaded.

    (use-package laas
      :config
      (aas-set-snippets 'laas-mode
        :cond #'laas-object-on-left-condition
        ",." (lambda () (interactive) (laas-wrap-previous-object "symbfit"))
        ".," (lambda () (interactive) (laas-wrap-previous-object "symbfit"))))

I made these variables for documentation generation.
They're not made to be mutated, unless maybe you want to disable an category of snippets.

**Comment by K-gihu** [comment]
@ymarco Thanks for your reply, I have created a pull request to add this configuration to README.

**Comment by ymarco** [comment]
See d6cd35d
