### ISSUE TITLE
option to disable some default snippets

### ISSUE THREAD

**Issue by matthuszagh** [tecosaur/LaTeX-auto-activating-snippets#2]
First of all, great job on this package! I've been hoping for something like this for a while.

Currently, all of the defined snippets are being activated by default in latex-mode with these lines:
```elisp
(apply #'aas-set-snippets 'latex-mode laas-basic-snippets)
(apply #'aas-set-snippets 'latex-mode laas-subscript-snippets)
(apply #'aas-set-snippets 'latex-mode laas-frac-snippet)
(apply #'aas-set-snippets 'latex-mode laas-accent-snippets)
```

I think it would be nice to be able to turn off this auto activation. The only way I can currently think to do this is to redefine these variables before loading the package (e.g., in `:init` of `use-package`), but then whatever I redefine them to be will still be applied. I think configuration here could be as simple as a `(defvar laas-apply-all-default-snippets t)` or something like that. That would give the user the option to disable activating them and then apply them selectively however (s)he wishes. But, the default behavior will be the same since most users will probably want them all applied without needing to change any settings. Let me know your thoughts.

**Comment by ymarco** [comment]
Disabling a whole pack of `laas-(basic|subscript|frac|accent)-snippets` should be doable by defining that variable to `nil` before the package loads.
If you wanna disable specific snippets, bind those keys to `nil`:
```emacs-lisp
(with-eval-after-load 'laas
  ;; using current master commit, which binds snippets to `laas-mode' instead of `latex-mode'
  (aas-set-snippets 'laas-mode 
    ";a" nil))
```
This example disables the `\alpha` snippet.

I should probably put this somewhere in the readme.

**Comment by ymarco** [comment]
> I should probably put this somewhere in the readme.

Added: https://github.com/ymarco/auto-activating-snippets/commit/e2b3edafd7aafa8c47833a70984d7404c607626c
