### ISSUE TITLE
How to input \(\) or \[\] or \{\}?

### ISSUE THREAD

**Issue by Lynntee** [tecosaur/LaTeX-auto-activating-snippets#24]
Many thanks for your wonderful work, I pretty like this package.

I am wondering how can I use snippet to automatically input `\(\)` or `\[\]` or `\{\}?`

To be more precise, I want to use `imh` as the trigger to be automatically expanded to be `\($0\).`
I used
``` emacs-lisp
(aas-set-snippets 'laas-mode "imh" (lambda () (interactive) (yas-expand-snippet "\\( $0 \\)") (laas--shut-up-smartparens)
```
but it cannot create `\(\)` but only `()`.

The same thing happens when I want to insert `\[\]` and `\{\}`.

I think the problem may be the difficulty to insert `\`?

Could you please provide some advice?

**Comment by ymarco** [comment]
I think this is related to
https://joaotavora.github.io/yasnippet/snippet-development.html#org0e7ccf8,
you need to escape the backslashes once again: "\\\\( $0 \\\\)".

**Comment by Lynntee** [comment]
It works for me now! Thank you very much!!
