### ISSUE TITLE
`jmath` snippet deletes the last character

### ISSUE THREAD

**Issue by cqy0280** [tecosaur/LaTeX-auto-activating-snippets#27]
![jmath](https://user-images.githubusercontent.com/40879856/147377242-c61f16f7-dbe7-4682-bb76-6f5ed3017909.gif)

As the title suggests, when the `jmath` snippet auto-expands (in both in-line and display math modes), it removes the last character `h` and replaces it by a `j` with a .5-second delay (see GIF above).

Haven't encountered this issue with any other snippets so far.

**Comment by ymarco** [comment]
Do you use evil-escape? I'm guessing it's causing the problem, see #20.

**Comment by cqy0280** [comment]
`(setq evil-escape-key-sequence 'nil)` solves the problem, thank you!
