### ISSUE TITLE
new feature and bindings e.g. for \dot{x}

### ISSUE THREAD

**Issue by fab6** [tecosaur/LaTeX-auto-activating-snippets#29]
Hi, 
I was just updating the package and found out that there are quite a few changes and quite a bit of further features :-)
As I used the package for quite some time now, I was pretty much used to the way of typing e.g. `\dot{x}` by using `. ` after the `x`.
It seems this is not available anymore... is there a way to add manually just like other `aas-set-snippets` snippets to reproduce the old way for  some selected bindings?

Thank you in advance!
Fab

**Comment by ymarco** [comment]
Ah yeah, sorry for the abrupt change. tecosaur originally added the ". " snippet and it has really annoyed me, expanding by surprise. You can still get \dot{} with ".. " and "'.", but here's the code to define ". " again.

(aas-set-snippets 'laas-mode
  :cond #'laas-object-on-left-condition
  ". " (lambda () (interactive)
         (laas-wrap-previous-object "dot")
         ;; if you want a space after the \dot{}, I think it's an improvement
         ;; and I changed ".. " to this behavior in the latest commit
         ;;(insert " ")
         ))

**Comment by fab6** [comment]
ok, great, thank you for the quick reply

**Comment by fab6** [comment]
one related question, what was the issue and surprise with the single ". " for the dot for you?

**Comment by ymarco** [comment]
I type a lot of things like \(\exists x \in \RR. x>0\) where I *want* the actual dot, not \dot{}.

**Comment by fab6** [comment]
ok, make sense, thanks
