### ISSUE TITLE
"-<" (including "<") not recognized in LaTex-mode

### ISSUE THREAD

**Issue by npencil** [tecosaur/LaTeX-auto-activating-snippets#31]
I use auctex LaTeX-mode, and turn on cdlatex

My init.el is like
```emacs-lisp
(use-package laas
  :ensure t
  :hook ((LaTeX-mode . laas-mode)
         (org-mode . laas-mode))
  :config
  (aas-set-snippets 'laas-mode
    :cond #'texmathp
    "-<" "\\leftarrow")
```

And no respond when typing "-<". Similarly, "<=" etc. failed.

Is this kind of snippet illegal?

**Comment by ymarco** [comment]
This is cdlatex's fault, binding "<" to cdlatex-pbb.

Either unbind <
  (define-key cdlatex-mode-map "<" nil)
or disable cdlatex's parens altogather
  (setq cdlatex-takeover-parenthesis nil)

**Comment by npencil** [comment]
Got it, thank you very much!
