### ISSUE TITLE
Using laas to activate yasnippet snippet

### ISSUE THREAD

**Issue by dalbandea** [tecosaur/LaTeX-auto-activating-snippets#33]
Hi, thank you for the amazing package!

I'm trying to use laas to auto activate a yasnippet snippet. However, doing this breaks the TAB motion inside the snippet.

I'm trying to auto-trigger this yasnippet snippet, which is defined in a separate file in my yasnippet directory:
```lisp
# -*- mode: snippet -*-
# name: begin-environment
# key: beg
# condition: (looking-back "^beg" nil)
# --
\begin{$1}
$2
\end{$1}
```

And to auto-trigger it I'm using this in the laas configuration:
```lisp
"beg" (lambda () (interactive)
                        (yas-expand-snippet "beg")
                        (yas-expand))
```

This way, writing "beg" at the beginning of a line it writes 

```tex
\begin{}

\end{}
```
with the cursor inside the `\begin` clause. Up to this point everything is as expected, but if I write something (e.g. `equation`) it gets written only in the `\begin` clause, and not in the `\end` close, as the yasnippet marker `$1` indicates. Also, pressing `TAB` just inserts a `TAB` instead of going to the next marker `$2`. Is there a way to make it work properly?

**Comment by ymarco** [comment]
Your usage of yas-expand-snippet is odd. To quote yas's source code:

  (defun yas-expand-snippet (snippet &optional start end expand-env)
    "Expand SNIPPET at current point.
  ...
  SNIPPET may be a snippet structure (e.g., as returned by
  `yas-lookup-snippet'), or just a snippet body (which is a string
  for normal snippets, and a list for command snippets)."
    ...)

Correct usage (as demonstrated in aas's and laas's readmes) to expand \begin{}...  would be

  (aas-set-snippets 'laas-mode
    :cond #'bolp
    "beg" (lambda () (interactive)
            (yas-expand-snippet "\\begin{$1}\n$2\n\\end{$1}\n")
            (laas--shut-up-smartparens)))

What your code does is first expand a snippet whose body is "beg", which means inserting the string "beg" into your buffer, and then call yas-expand which looks at the word before the cursor, "beg", as a snippet key. This should work but causes some weird behavior by chance?

If you want to expand snippet by name, I suggest looking up how doom-snippets does it:
https://github.com/doomemacs/snippets/blob/2d031f723164c6500ce68dcafe3dd30e6d3b23b1/doom-snippets-lib.el#L93


Sorry for the late response, the email apparently failed to send.

**Comment by dalbandea** [comment]
> What your code does is first expand a snippet whose body is "beg", which means inserting the string "beg" into your buffer, and then call yas-expand which looks at the word before the cursor, "beg", as a snippet key. This should work but causes some weird behavior by chance?

This is indeed what I intended. In this case the snippet example is small, but I have another more complex yas snippets with several lines and to put them as an "aas" snippet I would have to write them all on a line using "\n", which is quite unpleasant to edit, so that's why I wanted to just trigger my already defined yas snippet. My lisp knowledge is limited, but I'll try to look up how doom does it, thank you.

Is there another way of defining snippets so that multiline snippets are easy to edit? (more in the spirit of yasnippets or vim's ultisnips)

**Comment by ymarco** [comment]
> I would have to write them all on a line using "\n", which is quite unpleasant to edit
>
> Is there another way of defining snippets so that multiline snippets are easy to edit? (more in the spirit of yasnippets or vim's ultisnips)

Elisp accepts multiline strings, you can write

(aas-set-snippets 'laas-mode
    :cond #'bolp
    "beg" (lambda () (interactive)
            (yas-expand-snippet "\\begin{$1}
$2
\\end{$1}
")
            (laas--shut-up-smartparens)))



But I don't think it's much better.

**Comment by dalbandea** [comment]
Yes, I knew it worked, but as you say it's not much better since it doesn't keep good indentation out of the box I think. I'll close this and post a comment if I figure out an easy way to implement what I wanted, in case someone is interested. Thank you!
