### ISSUE TITLE
Delete and/or modify snippets

### ISSUE THREAD

**Issue by Sinthoras7** [tecosaur/LaTeX-auto-activating-snippets#37]
I personally like the Idea of this package - f.e. the annoying subscripts part is really useful, but I don't like the snippets provided, as they interfere with my own.

How can I modify them and delete some?

**Comment by ymarco** [comment]
For deleting, you can either define a new snippet with a nil expansion, or set the laas variable to nil before the package loads to disable the snippets in that variable. Take a look at other aas/laas issues, I've answered this with code snippets once or twice.

For modifying there's nothing special, just delete snippets and define new ones. Read the code and understand how they work.

**Comment by Sinthoras7** [comment]
Thank you!
