### ISSUE TITLE
unicode-math: how to use laas-unicode; smart-frac; and smart subscripts 

### ISSUE THREAD

**Issue by Sinthoras7** [tecosaur/LaTeX-auto-activating-snippets#40]
Hey, 

how can I use the laas-unicode file? I did not manage to use it. The simple use-package does not work, which makes sense, since laas-unicode is not provided as a package on elpa.

Also, I think it would be great, if the smart-frac also expands, when there is a unicode-greek-letter and then the `/`.
The same is also true for the smart subscripts. I think it would be the best to have a variable, where the user can add symbols to the list of symbols, for which the smart-frac and the subscripts work. 

I would implement those 2 things myself, as I think this only needs a few lines of code in the right conditions (I think `laas-object-on-left-condition` and `laas-auto-script-condition`) plus the definition of the list, but I know too few emacs-lisp to achieve it. Because of this I would be grateful, if someone implements these features and I think many more users can and will benefit from them.

Lastly, I want to thank you for this great package!

**Comment by ymarco** [comment]
Sinthoras ***@***.***> writes:

> Hey,
>
> how can I use the laas-unicode file? I did not manage to use it. The simple use-package does not work, which makes sense, since laas-unicode is
> not provided as a package on elpa.

Set laas-use-unicode to t.

> Also, I think it would be great, if the smart-frac also expands, when there is a unicode-greek-letter and then the /.
> The same is also true for the smart subscripts. I think it would be the best to have a variable, where the user can add symbols to the list of
> symbols, for which the smart-frac and the subscripts work.

I'll accept a PR. Would be best if non-unicode greek letter worked too to be consistent.

> I would implement those 2 things myself, as I think this only needs a few lines of code in the right conditions (I think
> laas-object-on-left-condition and laas-auto-script-condition) plus the definition of the list, but I know too few emacs-lisp to achieve it.
> Because of this I would be grateful, if someone implements these features and I think many more users can and will benefit from them.

**Comment by Sinthoras7** [comment]
Ah, thank you! 

I'll try to implement it and probably fail. Dear reader of the issue, if you have the knowledge and time/motivation to implement it, please file a pull-request :)
