### ISSUE TITLE
Smart Fraction snippet

### ISSUE THREAD

**Issue by Stefanomarton** [tecosaur/LaTeX-auto-activating-snippets#41]
Hey there, 
really good work, thank you. 
I'm sorry to bother but I can't get how to active the smart fraction function. I found it in the code but can't find any docs referring to it. 
Could you help me? 

I'm kind of new to emacs
Thanks 

~SM

**Comment by ymarco** [comment]
> Hey there,
> really good work, thank you.
> I'm sorry to bother but I can't get how to active the smart fraction function. I found it in the code but can't find any docs referring to it.
> Could you help me?

Would this be a good description for the readme?

> The infamous fraction
>
> Wrap the 'math object' before point with \frac, placing it in the
> numerator and moving the cursor to fill in the denominator.
>
> A math object is a letter, macro or something in parentheses (in which
> case the parens are removed when expanding).
>
> a/ ⇒ \frac{a}{}
> a b/ ⇒ a \frac{b}{}
> ab/ ⇒ \frac{ab}{}
> (a b) ⇒ \frac{a b}{}
>
>
> If there's no math object before point (e.g there's a space), don't
> expand /. if another / is typed, expand to a \frac without filling in
> the numerator."
>
> a // ⇒ a \frac{}{}


I also see now that "See the docs of `laas-frac-snippet’" leads nowhere, I'll fix the in-code docs shortly.

**Comment by Stefanomarton** [comment]
Thanks for the fast answer !! 

The readme description is good for me, but I can't get it working: if I type "a/" in a math block nothing happen.
The rest of the snippets all works, infact if I type "a //" it expand to "a \frac{}{}". And also snippet like "2qq" -> "\sqrt{2}" work like a charm.

This is the config I used
```
(use-package aas
  :hook (LaTeX-mode . aas-activate-for-major-mode)
  :hook (org-mode . aas-activate-for-major-mode)
  :config
  (aas-set-snippets 'text-mode
    ;; expand unconditionally
    ";o-" "ō"
    ";i-" "ī"
    ";a-" "ā"
    ";u-" "ū"
    ";e-" "ē")
  (aas-set-snippets 'latex-mode
    ;; set condition!
    :cond #'texmathp ; expand only while in math
    "supp" "\\supp"
    "On" "O(n)"
    "O1" "O(1)"
    "Olog" "O(\\log n)"
    "Olon" "O(n \\log n)"
    ;; bind to functions!
    "//" (lambda () (interactive)
           (yas-expand-snippet "\\frac{$1}{$2}$0"))
    "Span" (lambda () (interactive)
             (yas-expand-snippet "\\Span($1)$0")))
  ;; disable snippets by redefining them with a nil expansion
  (aas-set-snippets 'latex-mode
    "supp" nil))

(use-package laas
  :hook (LaTeX-mode . laas-mode)
  :config ; do whatever here
  (aas-set-snippets 'laas-mode
                    ;; set condition!
                    :cond #'texmathp ; expand only while in math
                    "supp" "\\supp"
                    "On" "O(n)"
                    "O1" "O(1)"
                    "Olog" "O(\\log n)"
                    "Olon" "O(n \\log n)"
                    ;; bind to functions!
                    "Sum" (lambda () (interactive)
                            (yas-expand-snippet "\\sum_{$1}^{$2} $0"))
                    "Span" (lambda () (interactive)
                             (yas-expand-snippet "\\Span($1)$0"))
                    ;; add accent snippets
                    :cond #'laas-object-on-left-condition
                    "qq" (lambda () (interactive) (laas-wrap-previous-object "sqrt"))))

```

And this is my config for emacs, kind of ugly, but I'm working on it
https://github.com/Stefanomarton/DotFiles/blob/master/.config/emacs/init.el

I don't if I'm doing something wrong.
Thanks 
~SM

**Comment by ymarco** [comment]
Could you try removing these 2 lines?



    "//" (lambda () (interactive)
           (yas-expand-snippet "\\frac{$1}{$2}$0"))

They might be overriding the normal / snippet. The readme's been changed since then exactly because // clashes with /.

**Comment by Stefanomarton** [comment]
yep, you are totally right !!

May his can also added to the readme?

Thank you, now I'm ready to do some homeworks 
~SM

**Comment by ymarco** [comment]
> May his can also added to the readme?

What do you mean? The problematic // snippet example was replaced months ago
