### ISSUE TITLE
About the complete for using this package.

### ISSUE THREAD

**Issue by hongyi-zhao** [tecosaur/LaTeX-auto-activating-snippets#43]
Though there is a [Sample Configuration](https://github.com/tecosaur/LaTeX-auto-activating-snippets#sample-configuration), but there are numerous snippets. How should I work out a complete configuration when using this package?

**Comment by ymarco** [comment]
> Though there is a Sample Configuration, but there are numerous snippets. How should I work out a complete configuration when using this package?

Not sure what you mean by "complete", but to get the default snippets just remove the :config part.

**Comment by hongyi-zhao** [comment]
What's the complete set of the default snippets?

**Comment by ymarco** [comment]
https://github.com/tecosaur/LaTeX-auto-activating-snippets/#snippets
