### ISSUE TITLE
How to disable some snippets in user configuration?

### ISSUE THREAD

**Issue by name8102** [tecosaur/LaTeX-auto-activating-snippets#45]
This plugin is very useful and convenient, but some snippets are realy annoying in particular environment, such as the `cb` expends to `^3` when I writing the tensor index. Is there a way to disable some snippets? 

```
(use-package! lass
  :config
  (setq laas-basic-snippets (remove "cb" laas-basic-snippets))
  (setq laas-basic-snippets (remove "^3" laas-basic-snippets))
)
```

I've added this code in my configuration file, but it didn't effect anything.

**Comment by ymarco** [comment]
Bind "cb" to nil.
Look at aas's documentation.
