### ISSUE TITLE
Feature request: Auto enlarge brackets on triggering fraction

### ISSUE THREAD

**Issue by itxprashant** [tecosaur/LaTeX-auto-activating-snippets#46]
For reference: https://github.com/artisticat1/obsidian-latex-suite?tab=readme-ov-file#auto-enlarge-brackets

It would be nice if the `point` is enclosed by delimiters such as `[` `(` or `\{` then fraction snippet would convert them to \\left... automatically.

**Comment by ymarco** [comment]
It's a nice feature, but I consider it outside of laas's scope. laas doesn't do that kind of parsing. We did it in [evil-tex](https://github.com/iyefrat/evil-tex/blob/2a3177c818f106e6c11032ac261f8691f5e11f74/evil-tex.el#L64-L157) and it took ~100 lines to code which I don't want to copy over.

You could patch `laas-smart-fraction` yourself with an advice to add it, though.
