### ISSUE TITLE
Org-mode support

### ISSUE THREAD

**Issue by maikol-solis** [tecosaur/LaTeX-auto-activating-snippets#5]
I hooked this package in `org-mode` in doom-emacs using this configuration:

```emacs-lisp
(use-package! laas
  :hook ((LaTeX-mode . laas-mode)
         (org-mode . laas-mode))
  :config
  (aas-set-snippets 'laas-mode
                    ;;expand unconditionally
                    "mk" (lambda () (interactive) (yas-expand-snippet "\$ $0\$"))
                    "dm" (lambda () (interactive) (yas-expand-snippet "\n\\[\n$0\n\\]"))
                    )
  )
```

If I write a line in regular text in `org-mode,` the `\dot{}` macro triggers no mater what. 

This is annoying because the combination `.[SPACE]`  is so natural in prose. 

For example if I write

`$alpha$-shape point.[SPACE]`

it transforms the text into 

`$alpha$-shape \dot{point} `

The ideal case will be that the combination `.[SPACE]` only triggers the `\dot{}` macro in math mode.

Thanks. 

_Edit: I changed the example._

**Comment by maikol-solis** [comment]
Reviewing a little I can confirm that in org-mode, all the shortcuts do not respect if they are in math or regular text.

**Comment by ymarco** [comment]
This package was develooped with only LaTeX in mind. Our method for checking if the cursor is in math, texmathp, comes from AUCTeX. I'm not surprised it messes up in Org.

Changing the conditions to support org-mode shouldn't be too hard though. Make a PR :)

```emacs-lisp
(defun laas-mathp ()
  "TODO docstring"
  (pcase major-mode
    ('latex-mode ...)
    ('org-mode ...)
    (_ nil)))
```

**Comment by tecosaur** [comment]
I'll have a go at this. As ymarco says, it shouldn't be to hard. `(org-element-type (org-element-at-point))` should do the trick.

**Comment by maikol-solis** [comment]
Thanks for the replies @ymarco  and @tecosaur. 

I work around the problem by using `\( \)` instead of `$ $` to surround inline latex code. 
 
> Changing the conditions to support org-mode shouldn't be too hard though. Make a PR :)

Yes, I will do. I have to learn how to proper code in lisp, but it's a good challenge though. 

Thanks again.
